name: Wake Streamlit App

on:
  schedule:
    - cron: "*/15 * * * *" 
  workflow_dispatch:

jobs:
  wakeup:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Streamlit App
        run: curl https://hpz-razorpay-cashfree-automation.streamlit.app/
